FORMER_TEAM_NAME_MAP = {
    'AFC Bournemouth': 'AFC Bournemouth',
    'Accrington FC': 'Accrington FC',
    'Arsenal FC': 'Arsenal FC',
    'Aston Villa': 'Aston Villa',
    'Barnsley FC': 'Barnsley FC',
    'Birmingham City': 'Birmingham City',
    'Birmingham FC': 'Birmingham City',
    'Blackburn Rovers': 'Blackburn Rovers',
    'Blackpool FC': 'Blackpool FC',
    'Bolton Wanderers': 'Bolton Wanderers',
    'Bradford City': 'Bradford City',
    'Bradford Park Avenue': 'Bradford Park Avenue',
    'Brentford FC': 'Brentford FC',
    'Brighton & Hove Albion': 'Brighton & Hove Albion',
    'Bristol City': 'Bristol City',
    'Burnley FC': 'Burnley FC',
    'Bury FC': 'Bury FC',
    'Cardiff City': 'Cardiff City',
    'Riverside A.F.C.': 'Cardiff City',
    'Carlisle United': 'Carlisle United',
    'Charlton Athletic': 'Charlton Athletic',
    'Chelsea FC': 'Chelsea FC',
    'Coventry City': 'Coventry City',
    'Singers F.C.': 'Coventry City',
    'Crystal Palace': 'Crystal Palace',
    'Darwen': 'Darwen',
    'Derby County': 'Derby County',
    'Everton FC': 'Everton FC',
    'St. Domingo FC': 'Everton FC',
    'Fulham FC': 'Fulham FC',
    'Glossop North End': 'Glossop North End',
    'Grimsby Town': 'Grimsby Town',
    'Huddersfield Town': 'Huddersfield Town',
    'Hull City': 'Hull City',
    'Ipswich Town': 'Ipswich Town',
    'Leeds United': 'Leeds United',
    'Leicester City': 'Leicester City',
    'Leicester Fosse': 'Leicester City',
    'Leyton Orient': 'Leyton Orient',
    'Clapton Orient': 'Leyton Orient',
    'Liverpool FC': 'Liverpool FC',
    'Luton Town': 'Luton Town',
    'Manchester City': 'Manchester City',
    'St. Marks': 'Manchester City',
    'Ardwick A.F.C.': 'Manchester City',
    'Manchester United': 'Manchester United',
    'Middlesbrough FC': 'Middlesbrough FC',
    'Millwall FC': 'Millwall FC',
    'Millwall Rovers': 'Millwall FC',
    'Millwall Athletic': 'Millwall FC',
    'Newcastle United': 'Newcastle United',
    'Newcastle East End F.C.': 'Newcastle United',
    'Newton Heath FC': 'Manchester United',
    'Northampton Town': 'Northampton Town',
    'Norwich City': 'Norwich City',
    'Nottingham Forest': 'Nottingham Forest',
    'Notts County': 'Notts County',
    'Oldham Athletic': 'Oldham Athletic',
    'Pine Villa F.C.': 'Oldham Athletic',
    'Oxford United': 'Oxford United',
    'Headington United': 'Oxford United',
    'Portsmouth FC': 'Portsmouth FC',
    'Portsmouth Royal Navy': 'Portsmouth FC',
    'Preston North End': 'Preston North End',
    'Queens Park Rangers': 'Queens Park Rangers',
    'Reading FC': 'Reading FC',
    'Sheffield United': 'Sheffield United',
    'Sheffield Wednesday': 'Sheffield Wednesday',
    'Wednesday Football Club': 'Sheffield Wednesday',
    'Small Heath Birmingham': 'Birmingham City',
    'Southampton FC': 'Southampton FC',
    "St. Mary's F.C": 'Southampton FC',
    "Southampton St. Mary's": 'Southampton FC',
    'Stoke City': 'Stoke City',
    'Stoke Ramblers': 'Stoke City',
    'Stoke F.C.': 'Stoke City',
    'Sunderland AFC': 'Sunderland AFC',
    'Sunderland and District Teachers AFC': 'Sunderland AFC',
    'Swansea City': 'Swansea City',
    'Swansea Town': 'Swansea City',
    'Swindon Town': 'Swindon Town',
    'Tottenham Hotspur': 'Tottenham Hotspur',
    'Hotspur FC': 'Tottenham Hotspur',
    'Watford FC': 'Watford FC',
    'Watford Rovers': 'Watford FC',
    'West Hertfordshire': 'Watford FC',
    'West Bromwich Albion': 'West Bromwich Albion',
    'West Bromwich Strollers': 'West Bromwich Albion',
    'West Ham United': 'West Ham United',
    'Thames Ironworks F.C.': 'West Ham United',
    'Wigan Athletic': 'Wigan Athletic',
    'Wimbledon FC': 'Wimbledon FC',
    'Wolverhampton Wanderers': 'Wolverhampton Wanderers',
    "St Luke's F.C": 'Wolverhampton Wanderers',
    'Woolwich Arsenal': 'Arsenal FC'
}
